name: Deploying file in AWS ec2
run-name: This files is deploy by ${{ github.actor }}

on:
    push:
        branches: [main, master]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v2

            - name: Print statement
              run: echo "I am Jit patel"

            - name: copy to ec2 using ssh
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.EC2_HOST}}
                  username: ${{secrets.EC2_USERNAME}}
                  key: ${{secrets.EC2_SSH_KEY}}
                  port: ${{secrets.EC2_SSH_PORT}}
                  source: "index.html"
                  target: "/tmp"

            - name: Print file
              run: ls -la /tmp

            - name: Deploy this file to Ec2
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.EC2_HOST}}
                  username: ${{secrets.EC2_USERNAME}}
                  key: ${{secrets.EC2_SSH_KEY}}
                  port: ${{secrets.EC2_SSH_PORT}}
                  script: |
                      whoami
                      sudo cp /tmp/index.html /usr/share/nginx/html/index.html
                      sudo systemctl reload nginx

            - name: Successfully Deploy
              run: echo "End of action"
